// <auto-generated />
using System;
using CoronaVirusApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoronaVirusApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200718194201_Initial-Migration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoronaVirusApi.Models.Continent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Continents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "آسیا"
                        },
                        new
                        {
                            Id = 2,
                            Name = "آمریکا"
                        },
                        new
                        {
                            Id = 3,
                            Name = "آفریقا"
                        },
                        new
                        {
                            Id = 4,
                            Name = "استرالیا"
                        },
                        new
                        {
                            Id = 5,
                            Name = "اروپا"
                        });
                });

            modelBuilder.Entity("CoronaVirusApi.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ContinentId")
                        .HasColumnType("int");

                    b.Property<int>("DeathNo")
                        .HasColumnType("int");

                    b.Property<int>("InfectedNo")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecoveredNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("RefreshDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ContinentId");

                    b.ToTable("Country");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContinentId = 1,
                            DeathNo = 13500,
                            InfectedNo = 300000,
                            Name = "ایران",
                            RecoveredNo = 250000,
                            RefreshDate = new DateTime(2020, 7, 18, 19, 42, 0, 800, DateTimeKind.Utc).AddTicks(7826)
                        },
                        new
                        {
                            Id = 2,
                            ContinentId = 2,
                            DeathNo = 13500,
                            InfectedNo = 300000,
                            Name = "ایالات متحده آمریکا",
                            RecoveredNo = 250000,
                            RefreshDate = new DateTime(2020, 7, 18, 19, 42, 0, 800, DateTimeKind.Utc).AddTicks(8584)
                        },
                        new
                        {
                            Id = 3,
                            ContinentId = 5,
                            DeathNo = 100000,
                            InfectedNo = 2000000,
                            Name = "انگلیس",
                            RecoveredNo = 1100000,
                            RefreshDate = new DateTime(2020, 7, 18, 19, 42, 0, 800, DateTimeKind.Utc).AddTicks(8597)
                        },
                        new
                        {
                            Id = 4,
                            ContinentId = 4,
                            DeathNo = 5000,
                            InfectedNo = 30000,
                            Name = "سیدنی",
                            RecoveredNo = 20000,
                            RefreshDate = new DateTime(2020, 7, 18, 19, 42, 0, 800, DateTimeKind.Utc).AddTicks(8599)
                        });
                });

            modelBuilder.Entity("CoronaVirusApi.Models.Country", b =>
                {
                    b.HasOne("CoronaVirusApi.Models.Continent", "Continent")
                        .WithMany("Countries")
                        .HasForeignKey("ContinentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
